from db.base_class import Base
from models.user import UserModel
from models.one_time_password import OneTimePasswordModel
from models.manual_customers import ManualCustomerModel
from models.shop_master import ShopMasterModel
from models.role import RoleModel
from models.user_role import UserRoleModel
from models.user_shop import UserShopModel
from models.customer_queue import CustomerQueueModel
from models.menu_master import MenuMasterModel