from crud.base import CRUDBase
from crud.user import User
from crud.otp import OTP
from crud.address import Address
from crud.contact_details import ContactDetails
from crud.shop import Shop
from crud.user_shop import UserShop
from crud.catalog import Catalog
from crud.customer_queue import CustomerQueue
from crud.bearer_token import BearerToken
