"""Initial Migration Added

Revision ID: b52bbaa1f189
Revises: 695c523b4655
Create Date: 2024-11-28 12:43:41.277187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b52bbaa1f189'
down_revision: Union[str, None] = '695c523b4655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_line_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address_line_2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), nullable=True),
    sa.Column('zipcode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cellphone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('workphone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fax', sa.VARCHAR(length=255), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('expected_time', sa.Time(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menu_master')
    op.add_column('shop_master', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('shop_master', sa.Column('modified_date', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'shop_master', 'address', ['address_id'], ['id'])
    op.create_foreign_key(None, 'shop_master', 'contact_details', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_master', type_='foreignkey')
    op.drop_constraint(None, 'shop_master', type_='foreignkey')
    op.drop_column('shop_master', 'modified_date')
    op.drop_column('shop_master', 'created_date')
    op.create_table('menu_master',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('expected_time', mysql.TIME(), nullable=False),
    sa.Column('shop_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('modified_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_master.id'], name='menu_master_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('catalog')
    op.drop_table('contact_details')
    op.drop_table('address')
    # ### end Alembic commands ###
