"""Initial Migration Added

Revision ID: d69136e16fe2
Revises: b52bbaa1f189
Create Date: 2024-12-13 13:04:27.472990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd69136e16fe2'
down_revision: Union[str, None] = 'b52bbaa1f189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_queue', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_queue', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
