from models.user import UserModel
from models.one_time_password import OneTimePasswordModel
from models.manual_customers import ManualCustomerModel
from models.role import RoleModel
from models.user_role import UserRoleModel
from models.user_shop import UserShopModel
from models.customer_queue import CustomerQueueModel
from models.catalog import CatalogModel
from models.address import AddressModel
from models.contact_details import ContactDetailsModel
from models.shop_master import ShopMasterModel
